<?php

namespace AppBundle\Repository;

/**
 * ArtistaEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistaEventoRepository extends \Doctrine\ORM\EntityRepository
{
}
