<?php

namespace AppBundle\Repository;

/**
 * ArtistaMusicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistaMusicaRepository extends \Doctrine\ORM\EntityRepository
{
}
