<?php

namespace AppBundle\Repository;

/**
 * CaracteristicaLocalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaracteristicaLocalRepository extends \Doctrine\ORM\EntityRepository
{
}
