<?php

namespace AppBundle\Repository;

/**
 * CategoriaNewsletter
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaNewsletter extends \Doctrine\ORM\EntityRepository
{
}
