<?php

namespace AppBundle\Repository;

/**
 * CategoriaAnuncioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaAnuncioRepository extends \Doctrine\ORM\EntityRepository
{
}
