<?php

namespace AppBundle\Repository;

/**
 * ConceptoPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptoPagoRepository extends \Doctrine\ORM\EntityRepository
{
}
