<?php

namespace AppBundle\Repository;

/**
 * DatosFacturacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatosFacturacionRepository extends \Doctrine\ORM\EntityRepository
{
}
