<?php

namespace AppBundle\Repository;

/**
 * DiaSemanaLocalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiaSemanaLocalRepository extends \Doctrine\ORM\EntityRepository
{
}
