<?php

namespace AppBundle\Repository;

/**
 * EnlaceCompraAlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnlaceCompraAlbumRepository extends \Doctrine\ORM\EntityRepository
{
}
