<?php

namespace AppBundle\Repository;

/**
 * EstadoEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoEventoRepository extends \Doctrine\ORM\EntityRepository
{
}
