<?php

namespace AppBundle\Repository;

/**
 * EstadoLocalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoLocalRepository extends \Doctrine\ORM\EntityRepository
{
}
