<?php

namespace AppBundle\Repository;

/**
 * EstadoUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoUsuarioRepository extends \Doctrine\ORM\EntityRepository
{
}
