<?php

namespace AppBundle\Repository;

/**
 * EstadoPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoPagoRepository extends \Doctrine\ORM\EntityRepository
{
}
