<?php

namespace AppBundle\Repository;

/**
 * EstadoAnuncioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoAnuncioRepository extends \Doctrine\ORM\EntityRepository
{
}
