<?php

namespace AppBundle\Repository;

/**
 * LocalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalRepository extends \Doctrine\ORM\EntityRepository
{
    public function buscarCompletados(){
        $em=$this->getEntityManager();
        $result=$em->createQuery("select local from AppBundle:Local local join local.estadoLocal estadoLocal where estadoLocal.slug='completado'")->getResult();
        return $result;
    }

    public function filtrarByParams($params){
        $em=$this->getEntityManager();
        $sql="select local from AppBundle:Local local where local.nombre like :nombre and  local.aforo>=:aforoMin and local.aforo<=:aforoMax";
        $result=$em->createQuery($sql)->setParameters($params)->getResult();
        return $result;
    }
}
