<?php

namespace AppBundle\Repository;

/**
 * SuscriptorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuscriptorRepository extends \Doctrine\ORM\EntityRepository
{
}
