<?php

namespace AppBundle\Repository;

/**
 * TemaAlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemaAlbumRepository extends \Doctrine\ORM\EntityRepository
{
}
