<?php

namespace AppBundle\Repository;

/**
 * TipoArtistaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoArtistaRepository extends \Doctrine\ORM\EntityRepository
{
}
