AppBundle\Entity\AdversimentsPhotos:
    type: entity
    table: adversiments_photos
    indexes:
        fk_adversiments_photos:
            columns:
                - adversiment_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        photo:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        name:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        alt:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        featuredPhoto:
            type: boolean
            nullable: false
            column: featured_photo
    manyToOne:
        adversiment:
            targetEntity: Adversiments
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                adversiment_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
