AppBundle\Entity\AlbumsBuyLinks:
    type: entity
    table: albums_buy_links
    indexes:
        fk_albums_buy_links:
            columns:
                - album_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        url:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    manyToOne:
        album:
            targetEntity: Albums
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                album_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
