AppBundle\Entity\Artists:
    type: entity
    table: artists
    indexes:
        fk_artists_users:
            columns:
                - user_id
        fk_artists_types:
            columns:
                - type_id
        fk_artists_status:
            columns:
                - status_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        nick:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        cacheMin:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: cache_min
        experience:
            type: datetime
            nullable: true
        bio:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
    manyToOne:
        status:
            targetEntity: ArtistsStatus
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                status_id:
                    referencedColumnName: id
            orphanRemoval: false
        type:
            targetEntity: ArtistsTypes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                type_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
