AppBundle\Entity\ArtistaMusica:
    type: entity
    table: artista_musica
    indexes:
        IDX_A048BC14AEB0CF13:
            columns:
                - artista_id
    uniqueConstraints:
        UNIQ_A048BC14989D9B62:
            columns:
                - slug
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        slug:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        artista:
            targetEntity: Artista
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                artista_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
