AppBundle\Entity\Bookings:
    type: entity
    table: bookings
    indexes:
        fk_bookings_users:
            columns:
                - user_id
        fk_bookings_events:
            columns:
                - event_id
        fk_bookings_status:
            columns:
                - status_id
        fk_bookings_payments:
            columns:
                - payment_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        numTickets:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: num_tickets
        total:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
        rates:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        card:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
    manyToOne:
        event:
            targetEntity: Events
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                event_id:
                    referencedColumnName: id
            orphanRemoval: false
        payment:
            targetEntity: Payments
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                payment_id:
                    referencedColumnName: id
            orphanRemoval: false
        status:
            targetEntity: BookingsStatus
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                status_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
