AppBundle\Entity\CaracteristicaLocal:
    type: entity
    table: caracteristica_local
    uniqueConstraints:
        slug:
            columns:
                - slug
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        slug:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToMany:
        localid:
            targetEntity: Local
            cascade: {  }
            fetch: LAZY
            mappedBy: caracteristicaLocalid
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
