AppBundle\Entity\Cities:
    type: entity
    table: cities
    indexes:
        fk_cities:
            columns:
                - province_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        city:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        slug:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        latitud:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        longitud:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        province:
            targetEntity: Provinces
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                province_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
