AppBundle\Entity\Contacto:
    type: entity
    table: contacto
    uniqueConstraints:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        telefono:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        facebook:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        twitter:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        instagram:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        linkedin:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        google:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        youtube:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
