AppBundle\Entity\HallsSchedules:
    type: entity
    table: halls_schedules
    indexes:
        fk_halls_schedules_weekdays:
            columns:
                - weekday_id
        fk_halls_schedules_halls:
            columns:
                - hall_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        open:
            type: boolean
            nullable: false
        price:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
        startTime:
            type: time
            nullable: true
            column: start_time
        endTime:
            type: time
            nullable: true
            column: end_time
    manyToOne:
        hall:
            targetEntity: HallsConcerts
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                hall_id:
                    referencedColumnName: id
            orphanRemoval: false
        weekday:
            targetEntity: HallsWeekdays
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                weekday_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
