AppBundle\Entity\HallsVideos:
    type: entity
    table: halls_videos
    indexes:
        fk_halls_videos:
            columns:
                - hall_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        video:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        name:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        alt:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        featuredVideo:
            type: boolean
            nullable: false
            column: featured_video
    manyToOne:
        hall:
            targetEntity: HallsConcerts
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                hall_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
