AppBundle\Entity\HallsStyles:
    type: entity
    table: halls_styles
    indexes:
        fk_halls_styles_ha:
            columns:
                - hall_id
        fk_halls_styles_st:
            columns:
                - style_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        hall:
            targetEntity: HallsConcerts
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                hall_id:
                    referencedColumnName: id
            orphanRemoval: false
        style:
            targetEntity: Styles
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                style_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
