AppBundle\Entity\HallsSchedulesException:
    type: entity
    table: halls_schedules_exception
    indexes:
        fk_halls_schedules_exception:
            columns:
                - hall_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        open:
            type: boolean
            nullable: false
        day:
            type: boolean
            nullable: false
        month:
            type: boolean
            nullable: false
        startTime:
            type: time
            nullable: true
            column: start_time
        endTime:
            type: time
            nullable: true
            column: end_time
        price:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
    manyToOne:
        hall:
            targetEntity: HallsConcerts
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                hall_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
