AppBundle\Entity\NewslettersSubscriber:
    type: entity
    table: newsletters_subscriber
    indexes:
        fk_newsletters_users:
            columns:
                - user_id
    uniqueConstraints:
        newsletters_subscriber_uniques_fields:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        active:
            type: boolean
            nullable: false
    manyToOne:
        user:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
