AppBundle\Entity\Notifications:
    type: entity
    table: notifications
    indexes:
        fk_notifications_users:
            columns:
                - user_id
        fk_notifications_types:
            columns:
                - type_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        readed:
            type: boolean
            nullable: true
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        extra:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
    manyToOne:
        type:
            targetEntity: NotificationsTypes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                type_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
