AppBundle\Entity\Payments:
    type: entity
    table: payments
    indexes:
        fk_payments_status:
            columns:
                - status_id
        fk_payments_types:
            columns:
                - type_id
        fk_payments_users:
            columns:
                - user_id
        fk_payments_events:
            columns:
                - event_id
    uniqueConstraints:
        payments_uniques_fields:
            columns:
                - transaction
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        transaction:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
        total:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
        rates:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
        createdAt:
            type: datetime
            nullable: false
            column: created_at
    manyToOne:
        event:
            targetEntity: Events
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                event_id:
                    referencedColumnName: id
            orphanRemoval: false
        status:
            targetEntity: PaymentsStatus
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                status_id:
                    referencedColumnName: id
            orphanRemoval: false
        type:
            targetEntity: PaymentsTypes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                type_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
