AppBundle\Entity\Provincia:
    type: entity
    table: Provincia
    indexes:
        IDX_516B70B0DA07061:
            columns:
                - idPais
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
    manyToOne:
        idpais:
            targetEntity: Pais
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idPais:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
