AppBundle\Entity\Publications:
    type: entity
    table: publications
    indexes:
        fk_publications_users:
            columns:
                - user_id
        fk_publications_status:
            columns:
                - status_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        text:
            type: text
            nullable: true
            length: 16777215
            options:
                fixed: false
        image:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
    manyToOne:
        status:
            targetEntity: PublicationsStatus
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                status_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
