AppBundle\Entity\UsersAddresses:
    type: entity
    table: users_addresses
    indexes:
        fk_users_addresses_country:
            columns:
                - country_id
        fk_users_addresses_province:
            columns:
                - province_id
        fk_users_addresses_city:
            columns:
                - city_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        address:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        postalCode:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: postal_code
    manyToOne:
        city:
            targetEntity: Cities
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                city_id:
                    referencedColumnName: id
            orphanRemoval: false
        country:
            targetEntity: Countries
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                country_id:
                    referencedColumnName: id
            orphanRemoval: false
        province:
            targetEntity: Provinces
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                province_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
