AppBundle\Entity\Viewers:
    type: entity
    table: viewers
    indexes:
        fk_viewers_users:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        sex:
            type: boolean
            nullable: false
        birthDate:
            type: date
            nullable: false
            column: birth_date
    manyToOne:
        user:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
