<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRbok1n6\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRbok1n6/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRbok1n6.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRbok1n6\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRbok1n6\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Rbok1n6',
    'container.build_id' => '8ed98764',
    'container.build_time' => 1529538023,
));
