<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMumssve\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMumssve/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMumssve.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMumssve\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerMumssve\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Mumssve',
    'container.build_id' => '735c3929',
    'container.build_time' => 1529601708,
));
