<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evento extends \AppBundle\Entity\Evento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'fechaCreacion', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'horaInicio', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'horaFin', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'comentarios', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'descripcion', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'diasVotacion', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'fechaVotacion', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'minimoEntradas', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'maxEntradas', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'gratuito', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'precioEntrada', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'porcientoLocal', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'totallocal', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'votos', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'comision', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'total', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'estadoEventoid', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'localid', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'estiloid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'fechaCreacion', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'horaInicio', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'horaFin', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'comentarios', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'descripcion', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'diasVotacion', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'fechaVotacion', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'minimoEntradas', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'maxEntradas', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'gratuito', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'precioEntrada', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'porcientoLocal', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'totallocal', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'votos', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'comision', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'total', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'estadoEventoid', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'localid', '' . "\0" . 'AppBundle\\Entity\\Evento' . "\0" . 'estiloid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Evento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreacion($fechaCreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreacion', [$fechaCreacion]);

        return parent::setFechaCreacion($fechaCreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreacion', []);

        return parent::getFechaCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraInicio($horaInicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraInicio', [$horaInicio]);

        return parent::setHoraInicio($horaInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraInicio', []);

        return parent::getHoraInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraFin($horaFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraFin', [$horaFin]);

        return parent::setHoraFin($horaFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraFin', []);

        return parent::getHoraFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setComentarios($comentarios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComentarios', [$comentarios]);

        return parent::setComentarios($comentarios);
    }

    /**
     * {@inheritDoc}
     */
    public function getComentarios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComentarios', []);

        return parent::getComentarios();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiasVotacion($diasVotacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiasVotacion', [$diasVotacion]);

        return parent::setDiasVotacion($diasVotacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiasVotacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiasVotacion', []);

        return parent::getDiasVotacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaVotacion($fechaVotacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaVotacion', [$fechaVotacion]);

        return parent::setFechaVotacion($fechaVotacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaVotacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaVotacion', []);

        return parent::getFechaVotacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setMinimoEntradas($minimoEntradas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMinimoEntradas', [$minimoEntradas]);

        return parent::setMinimoEntradas($minimoEntradas);
    }

    /**
     * {@inheritDoc}
     */
    public function getMinimoEntradas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMinimoEntradas', []);

        return parent::getMinimoEntradas();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaxEntradas($maxEntradas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaxEntradas', [$maxEntradas]);

        return parent::setMaxEntradas($maxEntradas);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxEntradas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxEntradas', []);

        return parent::getMaxEntradas();
    }

    /**
     * {@inheritDoc}
     */
    public function setGratuito($gratuito)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGratuito', [$gratuito]);

        return parent::setGratuito($gratuito);
    }

    /**
     * {@inheritDoc}
     */
    public function getGratuito()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGratuito', []);

        return parent::getGratuito();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecioEntrada($precioEntrada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecioEntrada', [$precioEntrada]);

        return parent::setPrecioEntrada($precioEntrada);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecioEntrada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecioEntrada', []);

        return parent::getPrecioEntrada();
    }

    /**
     * {@inheritDoc}
     */
    public function setPorcientoLocal($porcientoLocal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPorcientoLocal', [$porcientoLocal]);

        return parent::setPorcientoLocal($porcientoLocal);
    }

    /**
     * {@inheritDoc}
     */
    public function getPorcientoLocal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPorcientoLocal', []);

        return parent::getPorcientoLocal();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotallocal($totallocal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotallocal', [$totallocal]);

        return parent::setTotallocal($totallocal);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotallocal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotallocal', []);

        return parent::getTotallocal();
    }

    /**
     * {@inheritDoc}
     */
    public function setVotos($votos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVotos', [$votos]);

        return parent::setVotos($votos);
    }

    /**
     * {@inheritDoc}
     */
    public function getVotos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVotos', []);

        return parent::getVotos();
    }

    /**
     * {@inheritDoc}
     */
    public function setComision($comision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComision', [$comision]);

        return parent::setComision($comision);
    }

    /**
     * {@inheritDoc}
     */
    public function getComision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComision', []);

        return parent::getComision();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotal($total)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotal', [$total]);

        return parent::setTotal($total);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotal', []);

        return parent::getTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadoEventoid(\AppBundle\Entity\EstadoEvento $estadoEventoid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadoEventoid', [$estadoEventoid]);

        return parent::setEstadoEventoid($estadoEventoid);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadoEventoid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadoEventoid', []);

        return parent::getEstadoEventoid();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalid(\AppBundle\Entity\Local $localid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalid', [$localid]);

        return parent::setLocalid($localid);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalid', []);

        return parent::getLocalid();
    }

    /**
     * {@inheritDoc}
     */
    public function addEstiloid(\AppBundle\Entity\Estilo $estiloid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEstiloid', [$estiloid]);

        return parent::addEstiloid($estiloid);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEstiloid(\AppBundle\Entity\Estilo $estiloid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEstiloid', [$estiloid]);

        return parent::removeEstiloid($estiloid);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstiloid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstiloid', []);

        return parent::getEstiloid();
    }

}
