<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Anuncio extends \AppBundle\Entity\Anuncio implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Anuncio' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Anuncio' . "\0" . 'titulo', '' . "\0" . 'AppBundle\\Entity\\Anuncio' . "\0" . 'descripcion', '' . "\0" . 'AppBundle\\Entity\\Anuncio' . "\0" . 'precio', '' . "\0" . 'AppBundle\\Entity\\Anuncio' . "\0" . 'fechaPublicacion', '' . "\0" . 'AppBundle\\Entity\\Anuncio' . "\0" . 'fechaExpiracion', '' . "\0" . 'AppBundle\\Entity\\Anuncio' . "\0" . 'estadoAnuncioid', '' . "\0" . 'AppBundle\\Entity\\Anuncio' . "\0" . 'profesionalid', '' . "\0" . 'AppBundle\\Entity\\Anuncio' . "\0" . 'categoriaAnuncioid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Anuncio' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Anuncio' . "\0" . 'titulo', '' . "\0" . 'AppBundle\\Entity\\Anuncio' . "\0" . 'descripcion', '' . "\0" . 'AppBundle\\Entity\\Anuncio' . "\0" . 'precio', '' . "\0" . 'AppBundle\\Entity\\Anuncio' . "\0" . 'fechaPublicacion', '' . "\0" . 'AppBundle\\Entity\\Anuncio' . "\0" . 'fechaExpiracion', '' . "\0" . 'AppBundle\\Entity\\Anuncio' . "\0" . 'estadoAnuncioid', '' . "\0" . 'AppBundle\\Entity\\Anuncio' . "\0" . 'profesionalid', '' . "\0" . 'AppBundle\\Entity\\Anuncio' . "\0" . 'categoriaAnuncioid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Anuncio $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', [$titulo]);

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', []);

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecio($precio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecio', [$precio]);

        return parent::setPrecio($precio);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecio', []);

        return parent::getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaPublicacion($fechaPublicacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaPublicacion', [$fechaPublicacion]);

        return parent::setFechaPublicacion($fechaPublicacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaPublicacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaPublicacion', []);

        return parent::getFechaPublicacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaExpiracion($fechaExpiracion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaExpiracion', [$fechaExpiracion]);

        return parent::setFechaExpiracion($fechaExpiracion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaExpiracion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaExpiracion', []);

        return parent::getFechaExpiracion();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadoAnuncioid(\AppBundle\Entity\EstadoAnuncio $estadoAnuncioid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadoAnuncioid', [$estadoAnuncioid]);

        return parent::setEstadoAnuncioid($estadoAnuncioid);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadoAnuncioid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadoAnuncioid', []);

        return parent::getEstadoAnuncioid();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfesionalid(\AppBundle\Entity\Profesional $profesionalid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfesionalid', [$profesionalid]);

        return parent::setProfesionalid($profesionalid);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfesionalid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfesionalid', []);

        return parent::getProfesionalid();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoriaAnuncioid(\AppBundle\Entity\CategoriaAnuncio $categoriaAnuncioid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoriaAnuncioid', [$categoriaAnuncioid]);

        return parent::setCategoriaAnuncioid($categoriaAnuncioid);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoriaAnuncioid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoriaAnuncioid', []);

        return parent::getCategoriaAnuncioid();
    }

}
