<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Configuracion extends \AppBundle\Entity\Configuracion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Configuracion' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Configuracion' . "\0" . 'emailAdmin', '' . "\0" . 'AppBundle\\Entity\\Configuracion' . "\0" . 'comisionEvento', '' . "\0" . 'AppBundle\\Entity\\Configuracion' . "\0" . 'minimoComision', '' . "\0" . 'AppBundle\\Entity\\Configuracion' . "\0" . 'duracionAnuncios'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Configuracion' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Configuracion' . "\0" . 'emailAdmin', '' . "\0" . 'AppBundle\\Entity\\Configuracion' . "\0" . 'comisionEvento', '' . "\0" . 'AppBundle\\Entity\\Configuracion' . "\0" . 'minimoComision', '' . "\0" . 'AppBundle\\Entity\\Configuracion' . "\0" . 'duracionAnuncios'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Configuracion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailAdmin($emailAdmin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailAdmin', [$emailAdmin]);

        return parent::setEmailAdmin($emailAdmin);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailAdmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailAdmin', []);

        return parent::getEmailAdmin();
    }

    /**
     * {@inheritDoc}
     */
    public function setComisionEvento($comisionEvento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComisionEvento', [$comisionEvento]);

        return parent::setComisionEvento($comisionEvento);
    }

    /**
     * {@inheritDoc}
     */
    public function getComisionEvento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComisionEvento', []);

        return parent::getComisionEvento();
    }

    /**
     * {@inheritDoc}
     */
    public function setMinimoComision($minimoComision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMinimoComision', [$minimoComision]);

        return parent::setMinimoComision($minimoComision);
    }

    /**
     * {@inheritDoc}
     */
    public function getMinimoComision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMinimoComision', []);

        return parent::getMinimoComision();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuracionAnuncios($duracionAnuncios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuracionAnuncios', [$duracionAnuncios]);

        return parent::setDuracionAnuncios($duracionAnuncios);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuracionAnuncios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuracionAnuncios', []);

        return parent::getDuracionAnuncios();
    }

}
