<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pago extends \AppBundle\Entity\Pago implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Pago' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Pago' . "\0" . 'codigo', '' . "\0" . 'AppBundle\\Entity\\Pago' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\Pago' . "\0" . 'tipo', '' . "\0" . 'AppBundle\\Entity\\Pago' . "\0" . 'subtotal', '' . "\0" . 'AppBundle\\Entity\\Pago' . "\0" . 'idTransaccion', '' . "\0" . 'AppBundle\\Entity\\Pago' . "\0" . 'credito', '' . "\0" . 'AppBundle\\Entity\\Pago' . "\0" . 'estadoPagoid', '' . "\0" . 'AppBundle\\Entity\\Pago' . "\0" . 'usuarioid', '' . "\0" . 'AppBundle\\Entity\\Pago' . "\0" . 'impuestoid', '' . "\0" . 'AppBundle\\Entity\\Pago' . "\0" . 'conceptoPagoid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Pago' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Pago' . "\0" . 'codigo', '' . "\0" . 'AppBundle\\Entity\\Pago' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\Pago' . "\0" . 'tipo', '' . "\0" . 'AppBundle\\Entity\\Pago' . "\0" . 'subtotal', '' . "\0" . 'AppBundle\\Entity\\Pago' . "\0" . 'idTransaccion', '' . "\0" . 'AppBundle\\Entity\\Pago' . "\0" . 'credito', '' . "\0" . 'AppBundle\\Entity\\Pago' . "\0" . 'estadoPagoid', '' . "\0" . 'AppBundle\\Entity\\Pago' . "\0" . 'usuarioid', '' . "\0" . 'AppBundle\\Entity\\Pago' . "\0" . 'impuestoid', '' . "\0" . 'AppBundle\\Entity\\Pago' . "\0" . 'conceptoPagoid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pago $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigo($codigo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigo', [$codigo]);

        return parent::setCodigo($codigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigo', []);

        return parent::getCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', [$tipo]);

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', []);

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubtotal($subtotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubtotal', [$subtotal]);

        return parent::setSubtotal($subtotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubtotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubtotal', []);

        return parent::getSubtotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTransaccion($idTransaccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTransaccion', [$idTransaccion]);

        return parent::setIdTransaccion($idTransaccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTransaccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTransaccion', []);

        return parent::getIdTransaccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCredito($credito)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCredito', [$credito]);

        return parent::setCredito($credito);
    }

    /**
     * {@inheritDoc}
     */
    public function getCredito()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCredito', []);

        return parent::getCredito();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadoPagoid(\AppBundle\Entity\EstadoPago $estadoPagoid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadoPagoid', [$estadoPagoid]);

        return parent::setEstadoPagoid($estadoPagoid);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadoPagoid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadoPagoid', []);

        return parent::getEstadoPagoid();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioid(\AppBundle\Entity\Usuarios $usuarioid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioid', [$usuarioid]);

        return parent::setUsuarioid($usuarioid);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioid', []);

        return parent::getUsuarioid();
    }

    /**
     * {@inheritDoc}
     */
    public function setImpuestoid(\AppBundle\Entity\Impuesto $impuestoid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImpuestoid', [$impuestoid]);

        return parent::setImpuestoid($impuestoid);
    }

    /**
     * {@inheritDoc}
     */
    public function getImpuestoid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImpuestoid', []);

        return parent::getImpuestoid();
    }

    /**
     * {@inheritDoc}
     */
    public function setConceptoPagoid(\AppBundle\Entity\ConceptoPago $conceptoPagoid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConceptoPagoid', [$conceptoPagoid]);

        return parent::setConceptoPagoid($conceptoPagoid);
    }

    /**
     * {@inheritDoc}
     */
    public function getConceptoPagoid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConceptoPagoid', []);

        return parent::getConceptoPagoid();
    }

}
