<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Profesional extends \AppBundle\Entity\Profesional implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Profesional' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Profesional' . "\0" . 'nombreComercio', '' . "\0" . 'AppBundle\\Entity\\Profesional' . "\0" . 'fechaNacimento', '' . "\0" . 'AppBundle\\Entity\\Profesional' . "\0" . 'descripcion', '' . "\0" . 'AppBundle\\Entity\\Profesional' . "\0" . 'cif', '' . "\0" . 'AppBundle\\Entity\\Profesional' . "\0" . 'video', '' . "\0" . 'AppBundle\\Entity\\Profesional' . "\0" . 'datosFacturacionid', '' . "\0" . 'AppBundle\\Entity\\Profesional' . "\0" . 'usuarioid', '' . "\0" . 'AppBundle\\Entity\\Profesional' . "\0" . 'contactoid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Profesional' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Profesional' . "\0" . 'nombreComercio', '' . "\0" . 'AppBundle\\Entity\\Profesional' . "\0" . 'fechaNacimento', '' . "\0" . 'AppBundle\\Entity\\Profesional' . "\0" . 'descripcion', '' . "\0" . 'AppBundle\\Entity\\Profesional' . "\0" . 'cif', '' . "\0" . 'AppBundle\\Entity\\Profesional' . "\0" . 'video', '' . "\0" . 'AppBundle\\Entity\\Profesional' . "\0" . 'datosFacturacionid', '' . "\0" . 'AppBundle\\Entity\\Profesional' . "\0" . 'usuarioid', '' . "\0" . 'AppBundle\\Entity\\Profesional' . "\0" . 'contactoid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Profesional $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreComercio($nombreComercio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreComercio', [$nombreComercio]);

        return parent::setNombreComercio($nombreComercio);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreComercio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreComercio', []);

        return parent::getNombreComercio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaNacimento($fechaNacimento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaNacimento', [$fechaNacimento]);

        return parent::setFechaNacimento($fechaNacimento);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaNacimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaNacimento', []);

        return parent::getFechaNacimento();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCif($cif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCif', [$cif]);

        return parent::setCif($cif);
    }

    /**
     * {@inheritDoc}
     */
    public function getCif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCif', []);

        return parent::getCif();
    }

    /**
     * {@inheritDoc}
     */
    public function setVideo($video)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVideo', [$video]);

        return parent::setVideo($video);
    }

    /**
     * {@inheritDoc}
     */
    public function getVideo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideo', []);

        return parent::getVideo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatosFacturacionid(\AppBundle\Entity\DatosFacturacion $datosFacturacionid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatosFacturacionid', [$datosFacturacionid]);

        return parent::setDatosFacturacionid($datosFacturacionid);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatosFacturacionid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatosFacturacionid', []);

        return parent::getDatosFacturacionid();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioid(\AppBundle\Entity\Usuarios $usuarioid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioid', [$usuarioid]);

        return parent::setUsuarioid($usuarioid);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioid', []);

        return parent::getUsuarioid();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactoid(\AppBundle\Entity\Contacto $contactoid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactoid', [$contactoid]);

        return parent::setContactoid($contactoid);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactoid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactoid', []);

        return parent::getContactoid();
    }

}
