<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Factura extends \AppBundle\Entity\Factura implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'monto', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'numeroFactura', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'subtotal', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'comision', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'impuestoComision', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'impuestoSubtotal', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'pagoid', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'facturaid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'monto', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'numeroFactura', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'subtotal', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'comision', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'impuestoComision', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'impuestoSubtotal', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'pagoid', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'facturaid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Factura $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMonto($monto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMonto', [$monto]);

        return parent::setMonto($monto);
    }

    /**
     * {@inheritDoc}
     */
    public function getMonto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMonto', []);

        return parent::getMonto();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroFactura($numeroFactura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroFactura', [$numeroFactura]);

        return parent::setNumeroFactura($numeroFactura);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroFactura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroFactura', []);

        return parent::getNumeroFactura();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservaciones($observaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservaciones', [$observaciones]);

        return parent::setObservaciones($observaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservaciones', []);

        return parent::getObservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubtotal($subtotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubtotal', [$subtotal]);

        return parent::setSubtotal($subtotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubtotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubtotal', []);

        return parent::getSubtotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setComision($comision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComision', [$comision]);

        return parent::setComision($comision);
    }

    /**
     * {@inheritDoc}
     */
    public function getComision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComision', []);

        return parent::getComision();
    }

    /**
     * {@inheritDoc}
     */
    public function setImpuestoComision($impuestoComision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImpuestoComision', [$impuestoComision]);

        return parent::setImpuestoComision($impuestoComision);
    }

    /**
     * {@inheritDoc}
     */
    public function getImpuestoComision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImpuestoComision', []);

        return parent::getImpuestoComision();
    }

    /**
     * {@inheritDoc}
     */
    public function setImpuestoSubtotal($impuestoSubtotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImpuestoSubtotal', [$impuestoSubtotal]);

        return parent::setImpuestoSubtotal($impuestoSubtotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getImpuestoSubtotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImpuestoSubtotal', []);

        return parent::getImpuestoSubtotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setPagoid(\AppBundle\Entity\Pago $pagoid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPagoid', [$pagoid]);

        return parent::setPagoid($pagoid);
    }

    /**
     * {@inheritDoc}
     */
    public function getPagoid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPagoid', []);

        return parent::getPagoid();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacturaid(\AppBundle\Entity\Factura $facturaid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacturaid', [$facturaid]);

        return parent::setFacturaid($facturaid);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacturaid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacturaid', []);

        return parent::getFacturaid();
    }

}
