<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Local extends \AppBundle\Entity\Local implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'telefono', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'aforo', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'medidasEscenario', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'cacheMin', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'cacheMax', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'descripcion', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'direccion', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'idciudad', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'cif', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'anioApertura', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'mesApertura', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'video', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'iban', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'datosFacturacionid', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'usuarioid', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'contactoid', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'estadoLocalid', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'caracteristicaLocalid', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'estiloid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'telefono', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'aforo', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'medidasEscenario', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'cacheMin', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'cacheMax', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'descripcion', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'direccion', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'idciudad', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'cif', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'anioApertura', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'mesApertura', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'video', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'iban', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'datosFacturacionid', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'usuarioid', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'contactoid', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'estadoLocalid', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'caracteristicaLocalid', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'estiloid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Local $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setAforo($aforo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAforo', [$aforo]);

        return parent::setAforo($aforo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAforo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAforo', []);

        return parent::getAforo();
    }

    /**
     * {@inheritDoc}
     */
    public function setMedidasEscenario($medidasEscenario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMedidasEscenario', [$medidasEscenario]);

        return parent::setMedidasEscenario($medidasEscenario);
    }

    /**
     * {@inheritDoc}
     */
    public function getMedidasEscenario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedidasEscenario', []);

        return parent::getMedidasEscenario();
    }

    /**
     * {@inheritDoc}
     */
    public function setCacheMin($cacheMin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCacheMin', [$cacheMin]);

        return parent::setCacheMin($cacheMin);
    }

    /**
     * {@inheritDoc}
     */
    public function getCacheMin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCacheMin', []);

        return parent::getCacheMin();
    }

    /**
     * {@inheritDoc}
     */
    public function setCacheMax($cacheMax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCacheMax', [$cacheMax]);

        return parent::setCacheMax($cacheMax);
    }

    /**
     * {@inheritDoc}
     */
    public function getCacheMax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCacheMax', []);

        return parent::getCacheMax();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', [$direccion]);

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', []);

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdciudad($idciudad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdciudad', [$idciudad]);

        return parent::setIdciudad($idciudad);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdciudad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdciudad', []);

        return parent::getIdciudad();
    }

    /**
     * {@inheritDoc}
     */
    public function setCif($cif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCif', [$cif]);

        return parent::setCif($cif);
    }

    /**
     * {@inheritDoc}
     */
    public function getCif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCif', []);

        return parent::getCif();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnioApertura($anioApertura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnioApertura', [$anioApertura]);

        return parent::setAnioApertura($anioApertura);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnioApertura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnioApertura', []);

        return parent::getAnioApertura();
    }

    /**
     * {@inheritDoc}
     */
    public function setMesApertura($mesApertura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMesApertura', [$mesApertura]);

        return parent::setMesApertura($mesApertura);
    }

    /**
     * {@inheritDoc}
     */
    public function getMesApertura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMesApertura', []);

        return parent::getMesApertura();
    }

    /**
     * {@inheritDoc}
     */
    public function setVideo($video)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVideo', [$video]);

        return parent::setVideo($video);
    }

    /**
     * {@inheritDoc}
     */
    public function getVideo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideo', []);

        return parent::getVideo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIban($iban)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIban', [$iban]);

        return parent::setIban($iban);
    }

    /**
     * {@inheritDoc}
     */
    public function getIban()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIban', []);

        return parent::getIban();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatosFacturacionid(\AppBundle\Entity\DatosFacturacion $datosFacturacionid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatosFacturacionid', [$datosFacturacionid]);

        return parent::setDatosFacturacionid($datosFacturacionid);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatosFacturacionid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatosFacturacionid', []);

        return parent::getDatosFacturacionid();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioid(\AppBundle\Entity\Usuarios $usuarioid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioid', [$usuarioid]);

        return parent::setUsuarioid($usuarioid);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioid', []);

        return parent::getUsuarioid();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactoid(\AppBundle\Entity\Contacto $contactoid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactoid', [$contactoid]);

        return parent::setContactoid($contactoid);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactoid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactoid', []);

        return parent::getContactoid();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadoLocalid(\AppBundle\Entity\EstadoLocal $estadoLocalid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadoLocalid', [$estadoLocalid]);

        return parent::setEstadoLocalid($estadoLocalid);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadoLocalid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadoLocalid', []);

        return parent::getEstadoLocalid();
    }

    /**
     * {@inheritDoc}
     */
    public function addCaracteristicaLocalid(\AppBundle\Entity\CaracteristicaLocal $caracteristicaLocalid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCaracteristicaLocalid', [$caracteristicaLocalid]);

        return parent::addCaracteristicaLocalid($caracteristicaLocalid);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCaracteristicaLocalid(\AppBundle\Entity\CaracteristicaLocal $caracteristicaLocalid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCaracteristicaLocalid', [$caracteristicaLocalid]);

        return parent::removeCaracteristicaLocalid($caracteristicaLocalid);
    }

    /**
     * {@inheritDoc}
     */
    public function getCaracteristicaLocalid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaracteristicaLocalid', []);

        return parent::getCaracteristicaLocalid();
    }

    /**
     * {@inheritDoc}
     */
    public function addEstiloid(\AppBundle\Entity\Estilo $estiloid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEstiloid', [$estiloid]);

        return parent::addEstiloid($estiloid);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEstiloid(\AppBundle\Entity\Estilo $estiloid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEstiloid', [$estiloid]);

        return parent::removeEstiloid($estiloid);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstiloid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstiloid', []);

        return parent::getEstiloid();
    }

}
