<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuarios extends \AppBundle\Entity\Usuarios implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'password', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'salt', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'apellidos', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'rol', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'nif', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'fechaRegistro', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'direccionid', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'estadoUsuarioid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'password', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'salt', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'apellidos', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'rol', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'nif', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'fechaRegistro', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'direccionid', '' . "\0" . 'AppBundle\\Entity\\Usuarios' . "\0" . 'estadoUsuarioid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuarios $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalt($salt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalt', [$salt]);

        return parent::setSalt($salt);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidos($apellidos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidos', [$apellidos]);

        return parent::setApellidos($apellidos);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidos', []);

        return parent::getApellidos();
    }

    /**
     * {@inheritDoc}
     */
    public function setRol($rol)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRol', [$rol]);

        return parent::setRol($rol);
    }

    /**
     * {@inheritDoc}
     */
    public function getRol()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRol', []);

        return parent::getRol();
    }

    /**
     * {@inheritDoc}
     */
    public function setNif($nif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNif', [$nif]);

        return parent::setNif($nif);
    }

    /**
     * {@inheritDoc}
     */
    public function getNif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNif', []);

        return parent::getNif();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaRegistro($fechaRegistro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaRegistro', [$fechaRegistro]);

        return parent::setFechaRegistro($fechaRegistro);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaRegistro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaRegistro', []);

        return parent::getFechaRegistro();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccionid(\AppBundle\Entity\Direccion $direccionid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccionid', [$direccionid]);

        return parent::setDireccionid($direccionid);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccionid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccionid', []);

        return parent::getDireccionid();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadoUsuarioid(\AppBundle\Entity\EstadoUsuario $estadoUsuarioid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadoUsuarioid', [$estadoUsuarioid]);

        return parent::setEstadoUsuarioid($estadoUsuarioid);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadoUsuarioid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadoUsuarioid', []);

        return parent::getEstadoUsuarioid();
    }

}
